### ISSUE TITLE
Document wide mode

### ISSUE THREAD

**Issue by leadelazer** [brightlayer-ui/figma-plugins#19]
#### Describe the desired behavior
I want to be able to switch variants for components throughout the whole file, not just on the current page. 

#### Describe the current behavior
Currently the plugin affects a selection or all element visible on the current page. 

#### Is this request related to a current issue?
No

#### Additional Context
I'm aware that this might slow down the plugin a bit, but it would be worth so much. We have a large system with different scales and themes. However most of our styled components are linked to a set of root components which have different scales ("sizes") set up as a variant property. 

In our main UI kits we store all components on separate pages, so to rebuild a library with a new scale (--> eg. select variant "L" instead of "M" from root component) I have to go through all pages and artboards. Doing this for the whole document at once would save a lot of time and hundreds of clicks. 

There is another plugin called "[Bunch description change](https://www.figma.com/community/plugin/824407127671340098/Bunch-description-change)" which offers a document wide mode, looping through all components and variants. This would be ideal if combined with the variant switcher.

**Comment by huayunh** [comment]
Sounds fair. I can have a look into having an advanced option section for that.

**Comment by huayunh** [comment]
Fixed
