### ISSUE TITLE
Font styles switch

### ISSUE THREAD

**Issue by alexeiboronnikov** [brightlayer-ui/figma-plugins#25]
Rejected. Thanks! :)

**Comment by huayunh** [comment]
Hi Alexei and good to see you again 👋 

That is a little out of the scope for the "variant" switcher, but I get your concern. Maybe another plugin like this [Theme Switcher](https://www.figma.com/community/plugin/844318739744428676/Theme-Switcher) would help you with it?

**Comment by alexeiboronnikov** [comment]
Nice, will try, thanks a lot! :)
